.PHONY: all clean

PROJECT = yatka

$(PROJECT): main.c
	arm-linux-gcc -g -Ofast -march=armv5te -mtune=arm926ej-s -o $(PROJECT) main.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -D_BITTBOY

all: $(PROJECT)

clean:
	rm -rf $(PROJECT)
